// profiles.js – Profils de données pour le remplissage automatique
const PROFILES = {
  perso: {
    label: "👤 Profil Personnel",
    data: {
      prenom:         "Jean",
      firstname:      "Jean",
      nom:            "Dupont",
      lastname:       "Dupont",
      nom_complet:    "Jean Dupont",
      fullname:       "Jean Dupont",
      civilite:       "M.",
      genre:          "homme",
      date_naissance: "01/01/1990",
      birthdate:      "01/01/1990",
      lieu_naissance: "France",
      email:          "jean.dupont@example.com",
      telephone:      "06 00 00 00 00",
      mobile:         "06 00 00 00 00",
      adresse:        "10 rue Exemple",
      address:        "10 rue Exemple",
      adresse2:       "",
      ville:          "Paris",
      city:           "Paris",
      code_postal:    "75000",
      zipcode:        "75000",
      pays:           "France",
      country:        "France",
      region:         "Île-de-France",
      departement:    "Paris",
      conjoint_prenom: "Marie",
      conjoint_nom:    "Durand",
      conjoint_email:  ""
    }
  },
  pro: {
    label: "🏛️ Profil Professionnel",
    data: {
      prenom:         "Jean",
      firstname:      "Jean",
      nom:            "Dupont",
      lastname:       "Dupont",
      nom_complet:    "Jean Dupont",
      fullname:       "Jean Dupont",
      civilite:       "M.",
      email:          "jean.dupont.pro@example.com",
      telephone:      "06 00 00 00 00",
      organisation:   "Entreprise Exemple",
      organization:   "Entreprise Exemple",
      entreprise:     "Entreprise Exemple",
      company:        "Entreprise Exemple",
      service:        "Service Exemple",
      poste:          "Employé",
      fonction:       "Employé",
      siret:          "000 000 000 00000",
      adresse:        "Entreprise Exemple",
      address:        "Entreprise Exemple",
      ville:          "Paris",
      city:           "Paris",
      code_postal:    "75000",
      zipcode:        "75000",
      pays:           "France",
      country:        "France",
      region:         "Île-de-France",
      departement:    "Paris",
      employeur:      "Entreprise Exemple",
      statut:         "Salarié",
      grade:          "Employé"
    }
  }
};
